### ISSUE TITLE
[Bug]: Le jeu se bloque sans raison

### ISSUE THREAD

**Issue by edmondsnadane** [damienBodilis/pacman-for-firefox-os#1]
Le jeu bug presque systematiquement.
On ne peut pas terminer un niveau.

**Comment by guusgit** [comment]
solved by regenerating the modeTimes var

**Comment by edmondsnadane** [comment]
Avec la mise en place des difficultés , qui est effective grâce aux changements dans les Options du Menu. Le bug est réapparu.

-> ModeTimes qui plante !

**Comment by guusgit** [comment]
isn't that solved?

**Comment by edmondsnadane** [comment]
Solved
