### ISSUE TITLE
Bouton Pause

### ISSUE THREAD

**Issue by edmondsnadane** [damienBodilis/pacman-for-firefox-os#12]
Il faurdrait mettre un bouton pour faire pause pendant le jeu.

**Comment by guusgit** [comment]
http://stackoverflow.com/questions/16394092/how-to-resume-and-pause-a-timer-using-one-button-in-javascript 

you should look at this

**Comment by edmondsnadane** [comment]
Le bouton Pause n'existera pas.
Il n'a pas une grande utilité.
