### ISSUE TITLE
Système de creation de map en RANDOM

### ISSUE THREAD

**Issue by edmondsnadane** [damienBodilis/pacman-for-firefox-os#2]
Aujourd'hui, nous avons une map qui est ecrit en dur avec des Array.
Il faudrait créer un algo permettant de générer des maps en RANDOM.

**Comment by guusgit** [comment]
découplage de la map et du engine.js (mapgenerator.js)
Création de 2 niveaux supplémentaires manuellement
"bribes" d'algo pour génération random mais pas évident

**Comment by edmondsnadane** [comment]
Cette Issue n'a plus raison d'être. On part sur une solution de création manuel des maps. Et surtout le menu permet de choisir entre 3 choix de maps bien defini.
