### ISSUE TITLE
[Mobile] L'inputPlayer ne fonctionne pas dans les options

### ISSUE THREAD

**Issue by edmondsnadane** [damienBodilis/pacman-for-firefox-os#24]
Une fois le nom saisi dans les options, on n'arrive pas à valider le nom.

Sur PC, la fonction marche.

**Comment by Desiderius77** [comment]
Idem posez la question sur IRC : si c'est un bug connu vous le saurez tout de suite

**Comment by edmondsnadane** [comment]
Le problème a été reglé.
