### ISSUE TITLE
Le bouton exit ne fonctionne pas 

### ISSUE THREAD

**Issue by edmondsnadane** [damienBodilis/pacman-for-firefox-os#6]
Le bouton Exit ne permet pas de fermer la fenetre !

**Comment by guusgit** [comment]
to fix this issue, we have first to add the menu. so the exit button will be used to show the menu's canva

**Comment by edmondsnadane** [comment]
Le bouton EXIT n'existera plus.
Il sera remplacer par le bouton RESTART qui nous ramenera directement sur le menu.
